name: searchprice
description: Поиск_низких_цен


publish_to: 'none' 

version: 3.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.3
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^2.0.4
  in_app_purchase: ^0.5.2



  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  provider: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/1.png
    - lib/assets/images/2.png
    - lib/assets/images/3.png
    - lib/assets/images/22.png
    - lib/assets/images/23.png
    - lib/assets/images/33.png
    - lib/assets/images/vk.png
    - lib/assets/images/tg.png
    - lib/assets/images/viber.png
    - lib/assets/images/email.png
    - lib/assets/images/fb.png